CREATE TABLE public.usuario(
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(60) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);